addons:
  ssh_known_hosts: russellhay.com

language: go
go:
- tip
install: go get -v github.com/spf13/hugo
script:
- mkdir -p themes/stainless/static/css/
- sass themes/stainless/sass/main.scss:themes/stainless/static/css/style.css --style compressed
- hugo

notifications:
  email:
    on_faliure: always

before_install:
- openssl aes-256-cbc -K $encrypted_0f1905a07fca_key -iv $encrypted_0f1905a07fca_iv -in deploy.rsa.enc -out deploy.rsa -d
- gem install sass

before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy.rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy.rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet $TRAVIS_BUILD_DIR/public/ deploy@russellhay.com:/home/www/russellhay/
  on:
    branch: production
