baseurl = "https://russellhay.com"
languageCode = "en-us"
title = "Russell Hay"
theme = "stainless"

[params]
reel = "199474573"
description = "Russell Hay is a filmmaker, developer and traceur living in the Seattle area."

[taxonomies]
tag = "tags"
when = "when"
category = "categories"
ink = "inks"

[[menu.top]]
  name = "Blog"
  weight = -150
  identifier = "blog"
  url = "/blog"

[[menu.secondary]]
  name = "Projects"
  weight = -100
  identifier = "past"
  url = "/when/past"

[[menu.top]]
  name = "Film CV"
  weight = -50
  identifier = "filmcv"
  url = "/filmcv"

[[menu.top]]
  name = "Now"
  weight = 0
  identifier = "now"
  url = "/now"

[[menu.top]]
  name = "About"
  weight = 100
  identifier = "about"
  url = "/about"

[[menu.secondary]]
  name = "Contact"
  identifier = "contact"
  url = "/contact"
