# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Stainless"
license = "MIT"
licenselink = "https://github.com/stainless/stainless-hugo/blob/master/LICENSE.md"
description = ""
homepage = "http://stainless.themes.stainless.io/"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "Russell Hay"
  homepage = "http://russellhay.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
